/*
 * File: app/view/wndTipoCandidatoViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('voto.view.wndTipoCandidatoViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.wndtipocandidato',

    onTxtUsuarioNFocusleave1: function(component, event, eOpts) {
        Ext.Ajax.request({
            url: '../servidor/voto/tipocandidato/verificar',
            method:"post",
            params: {
                nombre: Ext.getCmp('txtDescripcionTC').getValue(),

            },
            success: function( result, request ) {
                var responseData = Ext.JSON.decode(result.responseText);
                if(responseData.failure){
                    Ext.Msg.alert('Error','El tipo de candidato ya existe');
                    Ext.getCmp('txtDescripcionTC').setValue('');
                    Ext.getCmp('txtDescripcionTC').reset();
                }

            },

            failure: function(response, opts) {

                console.log('server-side failure with status code ' + response.status);
            }
        });
    },

    onBtnCrearTCClick: function(button, e, eOpts) {
        var me = this;
        var forma = Ext.getCmp('frmTipoCandidato').getForm(),
            store = Ext.getStore('TipoCandidato');
        if(forma.isValid())
        {
            var values = forma.getValues();

            Ext.Ajax.request({
                url: '../servidor/voto/tipocandidato/create',
                method:"post",
                params: {
                    data: Ext.encode(values)

                },
                success: function( result, request ) {
                    var responseData = Ext.JSON.decode(result.responseText);
                    if(responseData.success){
                        Ext.Msg.alert('Alerta','El tipo de candidato ha sido creado satisfactoriamente');
                        Ext.getCmp('frmTipoCandidato').reset();
                        var store = Ext.getCmp('grdTipoCandidato').getStore();

                        store.removeAll();
                        store.load();
                        Ext.getCmp('wndTipoCandidato').close();


                    }
                    else{
                        Ext.Msg.alert('Error','No se ha podido ingresar el tipo de candidato');
                    }

                },

                failure: function(response, opts) {

                    console.log('server-side failure with status code ' + response.status);
                }
            });
        }
        else
        Ext.Msg.alert('Advertencia','Debe llenar todos los campos');
    },

    onBtnSalirTCClick: function(button, e, eOpts) {
        Ext.getCmp('wndTipoCandidato').close();
    }

});
