/*
 * File: app/view/pnlCarga.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('voto.view.pnlCarga', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.pnlcarga',

    requires: [
        'voto.view.pnlCargaViewModel',
        'voto.view.pnlCargaViewController',
        'Ext.panel.Panel',
        'Ext.button.Button',
        'Ext.toolbar.Toolbar'
    ],

    controller: 'pnlcarga',
    viewModel: {
        type: 'pnlcarga'
    },
    layout: 'fit',
    title: 'Carga de Estudiantes',

    items: [
        {
            xtype: 'panel',
            items: [
                {
                    xtype: 'panel',
                    height: 123,
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'button',
                            text: 'Cargar Estudiantes',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            id: 'btnDescargarP',
                            href: '../documentos/voto/DescargaPlantilla.zip',
                            iconAlign: 'right',
                            iconCls: 'x-fa fa-download',
                            text: 'Descargar Plantilla',
                            listeners: {
                                click: 'onBtnDescargarPClick'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});