/*
 * File: app/view/pnlTipoCandidatoViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('voto.view.pnlTipoCandidatoViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.pnltipocandidato',

    onBtnNuevoTipoClick: function(button, e, eOpts) {
        var win = Ext.create('voto.view.wndTipoCandidato');
        win.show();
    },

    onBtnEliminarTipoClick: function(button, e, eOpts) {
        var g = Ext.getCmp('grdTipoCandidato');
        var arrayKeys = g.getSelectionModel().selected.items;
        var indice = g.getSelectionModel().selectionStartIdx;
        if(arrayKeys.length === 0)
        Ext.Msg.alert('Error', 'Debe escoger un registro');
        else
        {
            var store = g.getStore();
            var rec = g.selection;
            Ext.Ajax.request({
                url: '../servidor/voto/tipocandidato/verificavoto',
                method:"post",
                params: {
                    id: rec.data.id
                },
                success: function( result, request ) {
                    var responseData = Ext.JSON.decode(result.responseText);
                    console.log(responseData);
                    if(responseData.success)
                    {
                        store.remove(rec);
                        store.sync(
                        {
                            params:{
                                id: rec.data.id
                            },
                            success: function(batch, success)
                            {
                                store.commitChanges();
                                store.load();
                                Ext.Msg.alert('Alerta', 'Se ha eliminado el registro exitosamente');
                            },

                            failure: function(batch, success)
                            {
                                Ext.Msg.alert('Error', 'Hubor un error');
                            }
                        });
                    }
                    else
                    {
                        Ext.Msg.alert('Alerta','Este registro tiene datos asociados.');
                    }
                },

                failure: function(response, opts) {
                    console.log('server-side failure with status code ' + response.status);
                }
            });

        }
    },

    onGrdTipoCandidatoAfterRender: function(component, eOpts) {
        var store = Ext.getCmp('grdTipoCandidato').getStore();
        store.removeAll();
        store.load();
    },

    onRowEditingEdit: function(editor, context, eOpts) {
        var me = this;
        var store = Ext.getCmp('grdTipoCandidato').getStore();
        var g = Ext.getCmp('grdTipoCandidato');
        var reco = g.selection;
        var id = reco.data.id;
        var arrayKeys = g.getSelectionModel().selected.items;

        if (context.record.modified)
        {
            var reco = context.record;
            store.add(reco);
            store.sync(
            {
                params:{
                    id: reco.data.id,
                    data: arrayKeys[0]


                },
                success: function(batch, success)
                {
                    store.commitChanges();
                    Ext.Msg.alert('Datos Guardados', 'Los datos se han guardado con éxito');
                    store.load();
                },

                failure: function(batch, success)
                {
                    Ext.Msg.alert('Error', 'Hubor un error');
                }
            });
        }
    }

});
