/*
 * File: app/view/pnlUsuarioSistemaViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('voto.view.pnlUsuarioSistemaViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.pnlusuariosistema',

    onBtnNuevoUsClick: function(button, e, eOpts) {
        var win = Ext.create('voto.view.wndUsuario');
        win.show();
    },

    onBtnEliminarUsClick: function(button, e, eOpts) {
        var g = Ext.getCmp('grdUsuarioSistema');
        var arrayKeys = g.getSelectionModel().selected.items;
        var indice = g.getSelectionModel().selectionStartIdx;
        if(arrayKeys.length === 0)
        Ext.Msg.alert('Error', 'Debe escoger un registro');
        else
        {
            var store = g.getStore();
            var rec = g.selection;


            store.remove(rec);
            store.sync(
            {
                params:{
                    usuario: rec.data.usuario
                },
                success: function(batch, success)
                {
                    store.commitChanges();
                    store.load();
                    Ext.Msg.alert('Alerta', 'Se ha eliminado el registro exitosamente');
                },

                failure: function(batch, success)
                {
                    Ext.Msg.alert('Error', 'Hubor un error');
                }
            });

        }
    },

    onGrdUsuarioSistemaAfterRender: function(component, eOpts) {
        var store = Ext.getCmp('grdUsuarioSistema').getStore();

        store.removeAll();
        store.load();
    }

});
