/*
 * File: app/view/pnlVotante.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('voto.view.pnlVotante', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.pnlvotante',

    requires: [
        'voto.view.pnlVotanteViewModel',
        'voto.view.pnlVotanteViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.form.field.ComboBox',
        'Ext.grid.column.Template',
        'Ext.XTemplate',
        'Ext.grid.column.Check',
        'Ext.form.field.Checkbox',
        'Ext.grid.plugin.RowEditing'
    ],

    controller: 'pnlvotante',
    viewModel: {
        type: 'pnlvotante'
    },
    layout: 'fit',
    title: 'Modificar Votante',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'textfield',
                    id: 'cedulavotante',
                    fieldLabel: 'Cédula'
                },
                {
                    xtype: 'button',
                    id: 'btnBuscar',
                    iconAlign: 'right',
                    iconCls: 'x-fa fa-search',
                    text: 'Buscar',
                    listeners: {
                        click: 'onBtnBuscarClick'
                    }
                },
                {
                    xtype: 'button',
                    id: 'btnEnviar',
                    iconAlign: 'right',
                    iconCls: 'x-fa fa-inbox',
                    text: 'Enviar Correo',
                    listeners: {
                        click: 'onBtnEnviarClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            id: 'grdVotante',
            title: '',
            forceFit: true,
            store: 'Votantes',
            viewConfig: {
                minHeight: 300
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'cedula',
                    text: 'Cedula'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'nombres',
                    text: 'Nombres',
                    editor: {
                        xtype: 'textfield'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'asociacion',
                    text: 'Asociacion',
                    editor: {
                        xtype: 'combobox',
                        displayField: 'facultad',
                        queryMode: 'local',
                        store: 'Facultad',
                        valueField: 'facultad'
                    }
                },
                {
                    xtype: 'templatecolumn',
                    dataIndex: 'email',
                    tpl: [
                        '<a href="mailto:{email}">{email}</a>'
                    ],
                    text: 'Email',
                    editor: {
                        xtype: 'textfield',
                        vtype: 'email'
                    }
                },
                {
                    xtype: 'checkcolumn',
                    disabled: true,
                    dataIndex: 'estado',
                    text: 'Estado',
                    editor: {
                        xtype: 'checkboxfield'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'clave',
                    text: 'MyColumn14'
                }
            ],
            plugins: [
                {
                    ptype: 'rowediting',
                    listeners: {
                        edit: 'onRowEditingEdit'
                    }
                }
            ]
        }
    ]

});