/*
 * File: app/view/vwprtLogin.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('voto.view.vwprtLogin', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.vwprtlogin',

    requires: [
        'voto.view.vwprtLoginViewModel',
        'voto.view.vwprtLoginViewController',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.form.Label',
        'Ext.form.field.Hidden'
    ],

    controller: 'vwprtlogin',
    viewModel: {
        type: 'vwprtlogin'
    },
    height: 250,
    width: 400,
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'center',
            layout: 'center',
            bodyStyle: 'background-color : #666666',
            items: [
                {
                    xtype: 'panel',
                    height: 250,
                    width: 600,
                    layout: 'border',
                    items: [
                        {
                            xtype: 'panel',
                            region: 'west',
                            html: '',
                            width: 200
                        },
                        {
                            xtype: 'form',
                            region: 'center',
                            id: 'FormaLogin',
                            bodyPadding: 10,
                            layout: {
                                type: 'vbox',
                                align: 'center',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    margin: '50 0 0 0',
                                    fieldLabel: 'Usuario',
                                    name: 'usuario',
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maxLength: 30
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '20 0 0 0',
                                    fieldLabel: 'Contraseña',
                                    name: 'clave',
                                    inputType: 'password',
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maxLength: 30,
                                    listeners: {
                                        specialkey: 'onTextfieldSpecialkey'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    margin: '20 0 0 0',
                                    width: 100,
                                    text: 'Aceptar',
                                    listeners: {
                                        click: 'onButtonClick'
                                    }
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    margin: 20,
                                    style: 'fontFamily : Georgia; font-style: italic; font-size: 14px',
                                    text: 'Desarrollado por la Dirección Informática | PUCE'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    flex: 1,
                                    width: 150,
                                    fieldLabel: 'Label',
                                    name: 'aplicacion',
                                    value: 'voto'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});