/*
 * File: app/view/wndTipoCandidato.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('voto.view.wndTipoCandidato', {
    extend: 'Ext.window.Window',
    alias: 'widget.wndtipocandidato',

    requires: [
        'voto.view.wndTipoCandidatoViewModel',
        'voto.view.wndTipoCandidatoViewController',
        'Ext.form.Panel',
        'Ext.form.field.Number',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button'
    ],

    controller: 'wndtipocandidato',
    viewModel: {
        type: 'wndtipocandidato'
    },
    height: 250,
    id: 'wndTipoCandidato',
    width: 400,
    title: 'Nuevo Tipo Candidato',

    items: [
        {
            xtype: 'form',
            id: 'frmTipoCandidato',
            bodyPadding: 10,
            layout: {
                type: 'vbox',
                align: 'center'
            },
            items: [
                {
                    xtype: 'textfield',
                    id: 'txtDescripcionTC',
                    fieldLabel: 'Descripcion',
                    name: 'descripcion',
                    allowBlank: false,
                    listeners: {
                        focusleave: 'onTxtUsuarioNFocusleave1'
                    }
                },
                {
                    xtype: 'numberfield',
                    id: 'txtVotosTC',
                    fieldLabel: 'Nro. Votos',
                    name: 'votos',
                    allowBlank: false,
                    minValue: 1
                },
                {
                    xtype: 'numberfield',
                    id: 'txtOrdenTC',
                    fieldLabel: 'Orden',
                    name: 'orden',
                    allowBlank: false,
                    minValue: 1
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            id: 'btnCrearTC',
                            text: 'Crear',
                            listeners: {
                                click: 'onBtnCrearTCClick'
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'btnSalirTC',
                            text: 'Atrás',
                            listeners: {
                                click: 'onBtnSalirTCClick'
                            }
                        },
                        {
                            xtype: 'tbfill'
                        }
                    ]
                }
            ]
        }
    ]

});