/*
 * File: app/view/pnlCorreosViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('voto.view.pnlCorreosViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.pnlcorreos',

    onId_correosClick: function(button, e, eOpts) {
        Ext.Ajax.request({
            url: '../servidor/voto/votante/enviar',
            method:"post",
            success: function( result, request ) {
                /*console.log(result);
                var aux = Ext.JSON.decode(result.responseText);
                if(aux.success){*/
                Ext.Msg.alert('Correos enviados','Se han enviado lo correos, verificar si no existen correos pendientes');
                Ext.Ajax.request({
                    url: '../servidor/voto/votante/correospendientes',
                    method:"post",
                    success: function( result, request ) {
                        var obj = Ext.JSON.decode(result.responseText);
                        Ext.getCmp('id_pendientes_correos').setValue(obj.data);
                        if(obj.data>0)
                        {
                            Ext.getCmp('id_correos').setDisabled(false);
                            Ext.getCmp('id_aviso_correo').setText('');
                        }
                        else{
                            Ext.getCmp('id_correos').setDisabled(true);
                            Ext.getCmp('id_aviso_correo').setText('No existen correos pendientes por enviar.');

                        }
                    },

                    failure: function(response, opts) {
                        console.log('server-side failure with status code ' + response.status);
                    }
                });
                /*}
                else{
                Ext.Msg.alert('Correos no enviados','No se han enviado lo correos, verificar correos pendientes');

                }*/

            },

            failure: function(response, opts) {
                console.log('server-side failure with status code ' + response.status);
            }
        });
    },

    onPanelAfterRender: function(component, eOpts) {
        Ext.Ajax.request({
            url: '../servidor/voto/votante/correospendientes',
            method:"post",
            success: function( result, request ) {
                var obj = Ext.JSON.decode(result.responseText);
                Ext.getCmp('id_pendientes_correos').setValue(obj.data);
                console.log(obj.data);
                if(obj.data>0)
                {
                    Ext.getCmp('id_correos').setDisabled(false);
                    Ext.getCmp('id_aviso_correo').setText('');
                }
                else{
                    Ext.getCmp('id_correos').setDisabled(true);
                    Ext.getCmp('id_aviso_correo').setText('No existen correos pendientes por enviar.');

                }
            },

            failure: function(response, opts) {
                console.log('server-side failure with status code ' + response.status);
            }
        });
    }

});
