/*
 * File: app/view/pnlLogout.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('voto.view.pnlLogout', {
    extend: 'Ext.window.Window',
    alias: 'widget.pnllogout',

    requires: [
        'voto.view.pnlLogoutViewModel',
        'voto.view.pnlLogoutViewController',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.form.field.Hidden'
    ],

    controller: 'pnllogout',
    viewModel: {
        type: 'pnllogout'
    },
    modal: true,
    height: 200,
    id: 'wndLogout',
    width: 325,
    layout: 'fit',
    title: 'Finalizar proceso de votación',

    items: [
        {
            xtype: 'form',
            id: 'frmLogout',
            margin: '15 0 0 0',
            title: '',
            layout: {
                type: 'vbox',
                align: 'center'
            },
            items: [
                {
                    xtype: 'textfield',
                    id: 'txtUsuario',
                    fieldLabel: 'Usuario',
                    labelWidth: 65,
                    name: 'usuario',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    id: 'txtClave',
                    fieldLabel: 'Clave',
                    labelWidth: 65,
                    name: 'clave',
                    inputType: 'password',
                    allowBlank: false,
                    listeners: {
                        specialkey: 'onTxtClaveSpecialkey'
                    }
                },
                {
                    xtype: 'button',
                    id: 'btnLgtAceptar',
                    text: 'Aceptar',
                    listeners: {
                        click: 'onBtnLgtAceptarClick'
                    }
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'aplicacion',
                    name: 'aplicacion',
                    value: 'voto'
                }
            ]
        }
    ]

});