/*
 * File: app/view/pnlProceso.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('voto.view.pnlProceso', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.pnlproceso',

    requires: [
        'voto.view.pnlProcesoViewModel',
        'voto.view.pnlProcesoViewController',
        'Ext.panel.Panel',
        'Ext.button.Button',
        'Ext.form.field.Display'
    ],

    controller: 'pnlproceso',
    viewModel: {
        type: 'pnlproceso'
    },
    layout: 'fit',
    title: 'Inicio de Votaciones',

    items: [
        {
            xtype: 'panel',
            items: [
                {
                    xtype: 'panel',
                    height: 125,
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'button',
                            text: 'Iniciar Proceso',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            id: 'id_proceso',
                            margin: '10 0 0 0'
                        }
                    ]
                }
            ]
        }
    ]

});