/*
 * File: app/view/wndUsuario.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('voto.view.wndUsuario', {
    extend: 'Ext.window.Window',
    alias: 'widget.wndusuario',

    requires: [
        'voto.view.wndUsuarioViewModel',
        'voto.view.wndUsuarioViewController',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button'
    ],

    controller: 'wndusuario',
    viewModel: {
        type: 'wndusuario'
    },
    height: 250,
    id: 'wndUsuario',
    width: 400,
    layout: 'center',
    title: 'Nuevo Usuario',

    items: [
        {
            xtype: 'form',
            id: 'frmUsuario',
            bodyPadding: 10,
            layout: {
                type: 'vbox',
                align: 'center'
            },
            items: [
                {
                    xtype: 'textfield',
                    id: 'txtUsuarioN',
                    fieldLabel: 'Usuario',
                    name: 'usuario',
                    allowBlank: false,
                    listeners: {
                        focusleave: 'onTxtUsuarioNFocusleave'
                    }
                },
                {
                    xtype: 'textfield',
                    id: 'txtNombreUs',
                    fieldLabel: 'Nombre',
                    name: 'nombre',
                    allowBlank: false
                },
                {
                    xtype: 'combobox',
                    id: 'cbRolUsuario',
                    fieldLabel: 'Rol',
                    name: 'id_rol',
                    allowBlank: false,
                    editable: false,
                    autoLoadOnValue: true,
                    displayField: 'descripcion',
                    store: 'Rol',
                    valueField: 'id'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            id: 'btnCrearUs',
                            text: 'Crear',
                            listeners: {
                                click: 'onBtnCrearUsClick'
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'btnSalirUs',
                            text: 'Atrás',
                            listeners: {
                                click: 'onBtnSalirUsClick'
                            }
                        },
                        {
                            xtype: 'tbfill'
                        }
                    ]
                }
            ]
        }
    ]

});