/*
 * File: app/view/vwprtLoginVotosViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('voto.view.vwprtLoginVotosViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.vwprtloginvotos',

    onClaveSpecialkey: function(field, e, eOpts) {
        //asigna la funcion del boton a la tecla ENTER
        if(e.getKey() == e.ENTER)
        {
            this.onBtnAceptarClick();
        }
    },

    onBtnAceptarClick: function(button, e, eOpts) {
        var forma = this.getView().down('#FormaLogin1').getForm();
        if(forma.isValid())
        {
            Ext.Ajax.request({
                url: '../servidor/voto/votante/revisa',
                method:"post",
                scope:this,
                params: {
                    cedula: Ext.getCmp('cedula').getValue(),
                    clave: Ext.getCmp('clave').getValue()
                },
                success: function( result, request )
                {
                    var responseData = Ext.decode(result.responseText);
                    if (!responseData.success) {
                        Ext.Msg.show//Mensaje de Error
                        (
                        {
                            title: 'Error',
                            msg: responseData.msn,
                            icon: Ext.Msg.ERROR,
                            buttons: Ext.Msg.OK
                        }
                        );
                    }
                    else{

                        this.getView().destroy();


                        VOTANTE = responseData.data[0];

                        Ext.Ajax.request({
                            url: '../servidor/voto/Tipocandidato/get',
                            method:"post",
                            success: function( result, request ) {
                                var responseData = Ext.JSON.decode(result.responseText);
                                TIPOS = responseData;
                                VOTOS = [];
                                for (var i = 0; i<TIPOS.data.length; i++) {
                                    if(!VOTOS[i])
                                    VOTOS[i] = [];
                                }
                                Ext.create('voto.view.vwprtPrincipal', {renderTo: Ext.getBody()});
                                Ext.getCmp('displayusuario2').setValue('TRIBUNAL: '+NOMBRE);
                                Ext.getCmp('displayusuario3').setValue('VOTANTE: '+VOTANTE.nombres);
                            },
                            failure: function(response, opts) {
                                console.log('server-side failure with status code ' + response.status);
                            }
                        });
                    }
                },

                failure: function(response, opts)
                {
                    Ext.Msg.show({
                        title:'Error',
                        msg: 'Usuario o clave mal ingresados',
                        buttons: Ext.Msg.OK,
                        icon: Ext.MessageBox.WARNING
                    });
                }
            });
        }
        else
        {
            Ext.Msg.alert('Error', 'Debe llenar todos los campos');
        }
    },

    onBtnSalirClick: function(button, e, eOpts) {
        LOGINVOTOS = this;
        if(!Ext.getCmp('pnlLogout'))
        {
            var win = Ext.create('voto.view.pnlLogout');
            win.show();
        }
    }

});
