/*
 * File: app/view/pnlNuevoViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('voto.view.pnlNuevoViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.pnlnuevo',

    onId_cedulaFocusleave: function(component, event, eOpts) {
        Ext.Ajax.request({
            url: '../servidor/voto/votante/verificar',
            method:"post",
            params: {
                cedula: Ext.getCmp('id_cedula').getValue(),

            },
            success: function( result, request ) {
                var responseData = Ext.JSON.decode(result.responseText);
                if(responseData.success){
                    Ext.Msg.alert('Error','El votante ya existe');
                    Ext.getCmp('id_cedula').setValue('');
                    Ext.getCmp('id_cedula').reset();
                }

            },

            failure: function(response, opts) {

                console.log('server-side failure with status code ' + response.status);
            }
        });

    },

    onBtnGuardarVClick: function(button, e, eOpts) {
        var me = this;
        var forma = Ext.getCmp('frmVotante').getForm(),
            store = Ext.getStore('Votantes');
        if(forma.isValid())
        {
            var values = forma.getValues();

            Ext.Ajax.request({
                url: '../servidor/voto/votante/create',
                method:"post",
                params: {
                    data: Ext.encode(values)

                },
                success: function( result, request ) {
                    var responseData = Ext.JSON.decode(result.responseText);
                    if(responseData.success){
                        Ext.Msg.alert('Alerta','El estudiante ha sido creado satisfactoriamente');
                        Ext.getCmp('frmVotante').reset();
                    }
                    else{
                        Ext.Msg.alert('Error','No se ha podido ingresar el usuario');
                    }

                },

                failure: function(response, opts) {

                    console.log('server-side failure with status code ' + response.status);
                }
            });
        }
        else
        Ext.Msg.alert('Advertencia','Debe llenar todos los campos');
    }

});
