/*
 * File: app/store/Facultad.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('voto.store.Facultad', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Array',
        'Ext.data.field.String'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Facultad',
            data: [
                {
                    facultad: 'Escuela de Bioanálisis'
                },
                {
                    facultad: 'Escuela de Trabajo Social'
                },
                {
                    facultad: 'Facultad de Arquitectura, Diseño y Artes'
                },
                {
                    facultad: 'Facultad de Ciencias Administrativas y Contables'
                },
                {
                    facultad: 'Facultad de Ciencias de la Educación'
                },
                {
                    facultad: 'Facultad de Ciencias Exactas y Naturales'
                },
                {
                    facultad: 'Facultad de Ciencias Filosóficas y Teológicas'
                },
                {
                    facultad: 'Facultad de Ciencias Humanas'
                },
                {
                    facultad: 'Facultad de Comunicación, Lingüística y Literatura'
                },
                {
                    facultad: 'Facultad de Economía'
                },
                {
                    facultad: 'Facultad de Enfermería'
                },
                {
                    facultad: 'Facultad de Ingeniería'
                },
                {
                    facultad: 'Facultad de Jurisprudencia'
                },
                {
                    facultad: 'Facultad de Medicina'
                },
                {
                    facultad: 'Facultad de Psicología'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'array'
                }
            },
            fields: [
                {
                    type: 'string',
                    name: 'facultad'
                }
            ]
        }, cfg)]);
    }
});