/*
 * File: app/view/wndCandidatoM.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('voto.view.wndCandidatoM', {
    extend: 'Ext.window.Window',
    alias: 'widget.wndcandidatom',

    requires: [
        'voto.view.wndCandidatoViewModel1',
        'voto.view.wndCandidatoViewController1',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    controller: 'wndcandidatom',
    viewModel: {
        type: 'wndcandidatom'
    },
    height: 409,
    id: 'wndCandidatoM',
    width: 400,
    layout: 'center',
    title: 'Modificar Candidato',

    items: [
        {
            xtype: 'form',
            reference: 'form',
            id: 'frmCandidatoM',
            bodyPadding: 10,
            layout: {
                type: 'vbox',
                align: 'center'
            },
            items: [
                {
                    xtype: 'textfield',
                    id: 'txtNombreCM',
                    fieldLabel: 'Candidato',
                    name: 'nombre',
                    allowBlank: false,
                    maskRe: /[a-zA-Z\s]/,
                    listeners: {
                        focusleave: 'onTxtNombreCMFocusleave'
                    }
                },
                {
                    xtype: 'combobox',
                    id: 'cbTipoCandidatoM',
                    fieldLabel: 'Tipo',
                    name: 'id_tipo_candidato',
                    allowBlank: false,
                    editable: false,
                    autoLoadOnValue: true,
                    displayField: 'descripcion',
                    queryMode: 'local',
                    store: 'TipoCandidato',
                    valueField: 'id'
                },
                {
                    xtype: 'button',
                    id: 'btnCargarF',
                    maxHeight: 30,
                    text: 'Cargar imágen',
                    listeners: {
                        click: 'onBtnCargarFClick'
                    }
                },
                {
                    xtype: 'panel',
                    height: 124,
                    id: 'id_panel_foto1',
                    margin: '10 0 0 10',
                    style: 'border-right:1px solid #919191; border-left:1px solid #919191; border-top:1px solid #919191; border-bottom:1px solid #919191;',
                    width: 106
                },
                {
                    xtype: 'container',
                    padding: 10,
                    layout: {
                        type: 'hbox',
                        align: 'middle',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            flex: 1,
                            itemId: 'cancelButton',
                            margin: 5,
                            text: 'Cancelar',
                            listeners: {
                                click: 'onCancelButtonClick'
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            formBind: true,
                            itemId: 'saveButton',
                            margin: 5,
                            text: 'Guardar',
                            listeners: {
                                click: 'onSaveButtonClick'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});