/*
 * File: app/view/pnlLogoutViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('voto.view.pnlLogoutViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.pnllogout',

    onTxtClaveSpecialkey: function(field, e, eOpts) {
        if(e.getKey() == e.ENTER)
        {
            this.onBtnLgtAceptarClick();
        }
    },

    onBtnLgtAceptarClick: function(button, e, eOpts) {
        var forma = this.getView().down('#frmLogout').getForm();
        if(forma.isValid())
        {
            Ext.Ajax.request({
                url: '../servidor/voto/usuariosistema/getRol',
                method:"post",
                params:{
                    usuario: Ext.getCmp('txtUsuario').getValue(),
                },
                success: function( result, request ) {
                    var responseData = Ext.JSON.decode(result.responseText);
                    if(responseData.success)
                    {
                        ROL = responseData.data[0].id_rol;
                        if(ROL === 2){
                            forma.submit(
                            {
                                url: '../servidor/login/revisa',
                                method: 'post',
                                scope: this,
                                success: function(response, opts)
                                {
                                    var responseData = opts.result.data;
                                    VERIFIED = responseData.verified;

                                    if(VERIFIED === true){
                                        Ext.Ajax.request
                                        (
                                        {
                                            url: '../servidor/login/logout',
                                            success:function(response,options)
                                            {
                                                var responseData = Ext.JSON.decode(response.responseText);
                                                if(responseData.success)
                                                {
                                                    Ext.getCmp('wndLogout').close();
                                                    LOGINVOTOS.getView().destroy();
                                                    Ext.create('voto.view.vwprtLogin', {renderTo: Ext.getBody()});
                                                }
                                            }
                                        }
                                        );
                                    }
                                    else{
                                        Ext.Msg.show({
                                            title:'Error',
                                            msg: 'Usted no tiene permisos para salir',
                                            buttons: Ext.Msg.OK,
                                            icon: Ext.MessageBox.WARNING
                                        });
                                    }
                                },

                                failure: function(response, opts)
                                {
                                    Ext.Msg.show({
                                        title:'Error',
                                        msg: 'Usuario o clave mal ingresados',
                                        buttons: Ext.Msg.OK,
                                        icon: Ext.MessageBox.WARNING
                                    });
                                }
                            });
                        }
                        else{
                            Ext.Msg.show({
                                title:'Error',
                                msg: 'Usted no tiene permisos para salir',
                                buttons: Ext.Msg.OK,
                                icon: Ext.MessageBox.WARNING
                            });
                        }
                    }
                    else
                    {
                        Ext.Msg.show({
                            title:'Error',
                            msg: 'Usuario o clave mal ingresados',
                            buttons: Ext.Msg.OK,
                            icon: Ext.MessageBox.WARNING
                        });
                    }
                },
                failure: function(response, opts) {
                    console.log('server-side failure with status code ' + response.status);
                }
            });
        }
        else
        {
            Ext.Msg.alert('Error', 'Debe llenar todos los campos');
        }
    }

});
